USE My_Music_DB
GO

CREATE TABLE Artists (
ArtistID INT PRIMARY KEY IDENTITY(1,1),
ArtistNickname NVARCHAR(20) NOT NULL,
MusicGroup BIT NOT NULL);

CREATE TABLE Groups (
GroupID INT PRIMARY KEY IDENTITY(1,1),
GroupName NVARCHAR(50) NOT NULL,
Country NVARCHAR(50) NOT NULL,
Followers INT NOT NULL);

CREATE TABLE Users (
UserID INT PRIMARY KEY IDENTITY(1,1),
UserName NVARCHAR(50) NOT NULL,
SubscriptionType NVARCHAR(20) NOT NULL);

CREATE TABLE Tracks (
TrackID INT IDENTITY(1,1) PRIMARY KEY,
Title NVARCHAR(150) NOT NULL,
Artist NVARCHAR(100) NOT NULL,
Genre NVARCHAR(50) NOT NULL,
DurationSeconds INT NOT NULL);

CREATE TABLE ListeningHistory (
HistoryID INT IDENTITY(1,1) PRIMARY KEY,
UserID INT FOREIGN KEY REFERENCES Users(UserID),
TrackID INT FOREIGN KEY REFERENCES Tracks(TrackID),
ListenDate DATETIME DEFAULT GETDATE());